### ISSUE TITLE
Crear una Sala

### ISSUE THREAD

**Issue by massich** [massich/Practica-PRO2#6]
Aconseguir escribir una sala.
1 - Crear sala
2 - mostrar sala

**Comment by martivall** [comment]
int main() {
  string a;
  bool fin = false;
  Matrix A(4,Row(3));
  for(int i = 0; i < 4; i++) {
      for(int j= 0; j < 3; j++) {
          A[i][j] == "NULL";
      }
  }
  for(int i = 0; i < 4; i++) {
      for(int j= 0; j < 3; j++) {
          cout << A[i][j] << " ";
      }
  }
  

}

**Comment by massich** [comment]
fixa't amb aquest i intenta fer algo similar.

`std::vector<int> v = {1, 2, 3, 4};`

**Comment by massich** [comment]
l'error del bintree tambe apareix [aqui](https://travis-ci.org/massich/Practica-PRO2/jobs/384168176#L433)

**Comment by massich** [comment]
Mira d'entendre aixo que funciona per una fila, i com ho passaries a Matriu

```cpp
#ifndef NO_DIAGRAM
#include <iostream>
#include <string>
#include <list>
#endif

using namespace std;

typedef std::vector<std::string> Row;

ostream& operator<<(ostream& os, const Row& row)
{
  for (const auto& element : row)
    if (not element.empty())
      os << element << " ";
    else
      os << "NULL ";
  return os;
}

int main() {
  string a;
  bool fin = false;

  Row r = {"aaa", "bbb", "ccc", std::string()};
  Row r2 = {"aaa", "bbb", "ccc"};
  std::cout << r << std::endl;
  std::cout << r2 << std::endl;

  r[2] = "xxxxx";
  std::cout << r << std::endl;

  std::cout << "XW23 NULL NULL" << std::endl;
  std::cout << "NULL NULL NULL" << std::endl;
  std::cout << "NULL NULL NULL" << std::endl;
  std::cout << "NULL NULL NULL" << std::endl;
  std::cout << "XW23 1" << std::endl;

}
```
